version: '3'
services:
    gym-duckietown-server:
        image: duckietown/gym-duckietown-server:2018.8.15
        networks:
        - gym-duckietown-net
        environment:
        - DISPLAY=:0
        - DUCKIETOWN_CHALLENGE=LF
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        ports:
        - "8902:8902"
        - "5558:5558"
        expose:
        - "8902"
        - "5558"

    gym-duckietown-ros:
        build: 
            context: .
            dockerfile: Dockerfile
        entrypoint: /ros_entrypoint.sh
        command: /bin/bash -c "source catkin_ws/devel/setup.bash && /usr/bin/python agent/rosbridge.py"
        depends_on:
        - "lanefollow"
        volumes:
        - .:/workspace/agent/
        networks:
        - gym-duckietown-net
        environment:
        - "ROS_MASTER_URI=http://lanefollow:11311"
        - DUCKIETOWN_SERVER=gym-duckietown-server
        - "HOSTNAME=default"
        expose:
        - "8902"
        - "5558"

    rosmonitor:
        image: ros:kinetic-perception
        networks:
        - gym-duckietown-net
        depends_on:
        - "lanefollow"
        command: bash -c "sleep 30 && rosbag record /default/line_detector_node/image_with_lines -O /home/rosbag/full.bag -l 1000"
        volumes:
        - /home/rosbag:/home/rosbag
        environment:
        - "ROS_MASTER_URI=http://lanefollow:11311"

    lanefollow:
        build: 
            context: .
            dockerfile: DockerfileRPI
        networks:
        - gym-duckietown-net
        command: /bin/bash -c "source /home/software/docker/env.sh && ./set_vehicle_name.sh && roslaunch /home/software/lf_slim.launch"
        entrypoint:
        - "qemu3-arm-static"
        environment:
        - "HOSTNAME=default"

networks:
  gym-duckietown-net:
