version: '3'
services:
    gym-duckietown-ros:
        build: 
            context: .
            dockerfile: Dockerfile
        command: /bin/bash -c "source catkin_ws/devel/setup.bash && /usr/bin/python rosagent.py"
        depends_on:
        - "lanefollow"
        volumes:
        - .:/workspace/agent/
        networks:
        - gym-duckietown-net
        entrypoint:
        - "qemu3-arm-static"
        environment:
        - "ROS_MASTER_URI=http://lanefollow:11311"
        - "HOSTNAME=default"

    lanefollow:
        build: 
            context: .
            dockerfile: DockerfileLFSlim
        networks:
        - gym-duckietown-net
        command: /bin/bash -c "source /home/software/docker/env.sh && ./set_vehicle_name.sh && roslaunch /home/software/lf_slim.launch"
        entrypoint:
        - "qemu3-arm-static"
        environment:
        - "HOSTNAME=default"

    # Optional: Just records a bagfile for monitoring purposes
    rosmonitor:
        image: ros:kinetic-perception
        networks:
        - gym-duckietown-net
        depends_on:
        - "lanefollow"
        command: bash -c "sleep 10 && rosbag record /default/line_detector_node/image_with_lines -O /tmp/rosbag/full.bag -l 1000"
        volumes:
        - /tmp/rosbag:/tmp/rosbag
        environment:
        - "ROS_MASTER_URI=http://lanefollow:11311"

    # Optional
    gym-duckietown-custom-catkin:
        build: 
            context: .
            dockerfile: Dockerfile
        command: /bin/bash -c "source catkin_ws/devel/setup.bash && rosrun dt_dependent_node dt_dependent_node.py"
        depends_on:
        - "lanefollow"
        volumes:
        - .:/workspace/agent/
        networks:
        - gym-duckietown-net
        entrypoint: "qemu3-arm-static"
        environment:
        - "ROS_MASTER_URI=http://lanefollow:11311"
        - "HOSTNAME=default"


networks:
  gym-duckietown-net:
